import { TenderDetail, TenderInvitation } from './tendering.api';

// Test data shared by the English and Arabic tendering specs.
export function invitation(overrides: Partial<TenderInvitation> = {}): TenderInvitation {
  return {
    id: 'i1',
    subcontractorId: 's1',
    subcontractorCode: 'ACME-01',
    subcontractorName: 'Acme Mechanical',
    currentStanding: 'Active',
    onApprovedShortlist: true,
    contactId: 'c1',
    recipientName: 'Rana Estimator',
    recipientEmail: 'rana@acme.example',
    status: 'Invited',
    expired: false,
    deliveryStatus: 'Sent',
    lastFailureCategory: null,
    issuedAtUtc: '2026-10-01T09:00:00Z',
    lastSentAtUtc: '2026-10-01T09:01:00Z',
    sentCount: 1,
    reminderCount: 0,
    firstOpenedAtUtc: null,
    lastOpenedAtUtc: null,
    openCount: 0,
    respondedAtUtc: null,
    declineReason: null,
    declineComment: null,
    revokedAtUtc: null,
    revokedByName: null,
    revocationReason: null,
    tokenGeneration: 1,
    hasActiveLink: true,
    sourcingApprovalRound: 1,
    canResend: true,
    canRemind: true,
    canRevoke: true,
    canRegenerate: true,
    canChangeRecipient: true,
    version: 'iv1',
    canCopyLink: true,
    firmLinkShown: false,
    ...overrides,
  };
}

export function tender(overrides: Partial<TenderDetail> = {}): TenderDetail {
  return {
    id: 't1',
    reference: 'TND-2026-0001',
    type: 'Rfq',
    status: 'Draft',
    lockReason: null,
    deadlineState: null,
    workPackage: {
      id: 'wp1',
      code: 'HVAC-01',
      title: 'HVAC installation',
      status: 'Active',
      projectId: 'p1',
      projectCode: 'TOWER',
      projectName: 'Tower One',
      projectStatus: 'Active',
    },
    title: 'HVAC installation',
    scopeInstructions: 'Supply and install.',
    currency: 'EGP',
    bidValidityDays: 90,
    technicalProposalRequired: true,
    durationRequired: true,
    pricing: null,
    terms: null,
    pricingBasisRequired: false,
    requiredDocuments: ['Priced BOQ'],
    submissionInstructions: null,
    submissionDeadline: {
      utc: '2026-10-15T11:00:00Z',
      local: '2026-10-15T14:00',
      offset: '+03:00',
    },
    originalSubmissionDeadline: null,
    questionsDeadline: null,
    timeZoneId: 'Asia/Riyadh',
    contactName: 'Maha Manager',
    contactEmail: 'maha@delta.example',
    contactPhone: null,
    emailLocale: 'en',
    reminderDays: [3, 1],
    reminders: [],
    missingForPublication: [],
    documents: [],
    invitations: [
      invitation({
        status: 'Prepared',
        deliveryStatus: 'NotSent',
        lastSentAtUtc: null,
        sentCount: 0,
      }),
    ],
    counts: {
      total: 1,
      queued: 0,
      sent: 0,
      failed: 0,
      opened: 0,
      intendsToBid: 0,
      declined: 0,
      noResponse: 0,
      revoked: 0,
    },
    approvedShortlist: {
      approvalId: 'a1',
      round: 1,
      approvedAtUtc: '2026-09-30T10:00:00Z',
      approvedByName: 'Maha Manager',
      members: [
        {
          subcontractorId: 's1',
          code: 'ACME-01',
          legalName: 'Acme Mechanical',
          currentStanding: 'Active',
          alreadyInvited: true,
          contacts: [
            {
              contactId: 'c1',
              name: 'Rana Estimator',
              jobTitle: null,
              email: 'rana@acme.example',
              isPrimary: true,
            },
            {
              contactId: 'c2',
              name: 'Omar Owner',
              jobTitle: null,
              email: 'omar@acme.example',
              isPrimary: false,
            },
          ],
        },
        {
          subcontractorId: 's2',
          code: 'BETA',
          legalName: 'Beta Cooling',
          currentStanding: 'Active',
          alreadyInvited: false,
          contacts: [
            {
              contactId: 'c3',
              name: 'Bilal',
              jobTitle: null,
              email: 'bilal@beta.example',
              isPrimary: true,
            },
          ],
        },
      ],
    },
    currentRevision: 0,
    publishedAtUtc: null,
    publishedByName: null,
    sourcingApprovalRound: null,
    cancelledAtUtc: null,
    cancelledByName: null,
    cancellationReason: null,
    createdAtUtc: '2026-09-30T11:00:00Z',
    updatedAtUtc: '2026-09-30T11:00:00Z',
    version: 'v1',
    ...overrides,
  };
}

export function published(overrides: Partial<TenderDetail> = {}): TenderDetail {
  return tender({
    status: 'Published',
    lockReason: 'tender.published_read_only',
    deadlineState: 'Open',
    currentRevision: 1,
    publishedAtUtc: '2026-10-01T09:00:00Z',
    publishedByName: 'Maha Manager',
    sourcingApprovalRound: 1,
    invitations: [invitation()],
    counts: {
      total: 1,
      queued: 0,
      sent: 1,
      failed: 0,
      opened: 0,
      intendsToBid: 0,
      declined: 0,
      noResponse: 1,
      revoked: 0,
    },
    ...overrides,
  });
}
