// CF-100 (ADR-160, red-team B-100-1): audit actions read as events. Every action the backend writes to the company audit log has a
// curated label in both languages (the committed list core/localization/audit-actions.json is the emitted set; a spec and an architecture test
// keep the three equal). Anything else reads as its object plus "event" — never an English phrase in Arabic, never the raw code; the code
// stays available as the tooltip and in the export.
import AUDIT_ACTIONS from '../../core/localization/audit-actions.json';

/** The committed list of tenant audit actions the backend emits. */
export const EMITTED_AUDIT_ACTIONS: readonly string[] = AUDIT_ACTIONS;

// Built on first use for the translations then loaded (a spec may load the Arabic catalogue after this module was imported).
let cache: {
  readonly translations: unknown;
  readonly actions: Readonly<Record<string, string>>;
  readonly objects: Readonly<Record<string, string>>;
} | null = null;

function catalogue() {
  const translations = ($localize as { TRANSLATIONS?: unknown }).TRANSLATIONS;
  if (cache && cache.translations === translations) return cache;
  const built = { translations, actions: actions(), objects: objects() };
  cache = built;
  return built;
}

const actions = (): Readonly<Record<string, string>> => ({
  'addendum.acknowledged': $localize`:@@auditAction.addendum_acknowledged:Addendum acknowledged by the firm`,
  'addendum.discarded': $localize`:@@auditAction.addendum_discarded:Draft addendum discarded`,
  'addendum.document_added': $localize`:@@auditAction.addendum_document_added:Document added to an addendum`,
  'addendum.document_removed': $localize`:@@auditAction.addendum_document_removed:Document removed from an addendum`,
  'addendum.drafted': $localize`:@@auditAction.addendum_drafted:Addendum drafted`,
  'addendum.issued': $localize`:@@auditAction.addendum_issued:Addendum issued`,
  'addendum.updated': $localize`:@@auditAction.addendum_updated:Draft addendum updated`,
  'admin.recovered': $localize`:@@auditAction.admin_recovered:Company Admin access recovered by the provider`,
  'approval_rule.created': $localize`:@@auditAction.approval_rule_created:Approval rule created`,
  'approval_rule.updated': $localize`:@@auditAction.approval_rule_updated:Approval rule updated`,
  'approval_rule.weakened': $localize`:@@auditAction.approval_rule_weakened:Approval rule weakened (confirmed with a reason)`,
  'audit.exported': $localize`:@@auditAction.audit_exported:Audit log exported`,
  'award.accepted': $localize`:@@auditAction.award_accepted:Award accepted by the firm`,
  'award.declined': $localize`:@@auditAction.award_declined:Award declined by the firm`,
  'award.issued': $localize`:@@auditAction.award_issued:Award issued`,
  'award.notices_released': $localize`:@@auditAction.award_notices_released:Outcome notices released`,
  'award.reserves_released': $localize`:@@auditAction.award_reserves_released:Reserve firms told the outcome`,
  'award.summary_exported': $localize`:@@auditAction.award_summary_exported:Award summary exported`,
  'award.withdrawal_rejected': $localize`:@@auditAction.award_withdrawal_rejected:Award withdrawal rejected`,
  'award.withdrawal_requested': $localize`:@@auditAction.award_withdrawal_requested:Award withdrawal requested`,
  'award.withdrawn': $localize`:@@auditAction.award_withdrawn:Award withdrawn`,
  'bid.amendment_discarded': $localize`:@@auditAction.bid_amendment_discarded:Bid amendment discarded`,
  'bid.amendment_started': $localize`:@@auditAction.bid_amendment_started:Bid amendment started`,
  'bid.attachment_added': $localize`:@@auditAction.bid_attachment_added:File attached to a bid`,
  'bid.attachment_refused': $localize`:@@auditAction.bid_attachment_refused:Bid file refused`,
  'bid.attachment_removed': $localize`:@@auditAction.bid_attachment_removed:File removed from a bid`,
  'bid.outside_portal_confirmed': $localize`:@@auditAction.bid_outside_portal_confirmed:Bid received outside the portal confirmed`,
  'bid.outside_portal_file_opened': $localize`:@@auditAction.bid_outside_portal_file_opened:File of a bid received outside the portal opened`,
  'bid.outside_portal_recorded': $localize`:@@auditAction.bid_outside_portal_recorded:Bid received outside the portal recorded`,
  'bid.outside_portal_viewed': $localize`:@@auditAction.bid_outside_portal_viewed:Bid received outside the portal viewed`,
  'bid.resubmitted': $localize`:@@auditAction.bid_resubmitted:Bid revised and resubmitted`,
  'bid.resumed': $localize`:@@auditAction.bid_resumed:Bid resumed after declining`,
  'bid.started': $localize`:@@auditAction.bid_started:Bid started`,
  'bid.submission_refused': $localize`:@@auditAction.bid_submission_refused:Bid submission refused`,
  'bid.submitted': $localize`:@@auditAction.bid_submitted:Bid submitted`,
  'bid.withdrawn': $localize`:@@auditAction.bid_withdrawn:Bid withdrawn`,
  'category_mapping.cleared': $localize`:@@auditAction.category_mapping_cleared:Category mapping cleared`,
  'category_mapping.set': $localize`:@@auditAction.category_mapping_set:Category mapping set`,
  'clarification.answered': $localize`:@@auditAction.clarification_answered:Question answered`,
  'clarification.asked': $localize`:@@auditAction.clarification_asked:Question asked`,
  'clarification.published': $localize`:@@auditAction.clarification_published:Answer published to all firms`,
  'company.exported': $localize`:@@auditAction.company_exported:Company data exported`,
  'company.governance_changed': $localize`:@@auditAction.company_governance_changed:Procurement governance changed`,
  'company_email.credentials_replaced': $localize`:@@auditAction.company_email_credentials_replaced:Mail server credentials replaced`,
  'company_email.server_configured': $localize`:@@auditAction.company_email_server_configured:Mail server set up`,
  'company_email.server_disabled': $localize`:@@auditAction.company_email_server_disabled:Mail server turned off`,
  'company_email.server_enabled': $localize`:@@auditAction.company_email_server_enabled:Mail server turned on`,
  'company_email.server_tested': $localize`:@@auditAction.company_email_server_tested:Mail server tested`,
  'company_email.server_updated': $localize`:@@auditAction.company_email_server_updated:Mail server settings changed`,
  'company_profile.currency_changed': $localize`:@@auditAction.company_profile_currency_changed:Default currency changed`,
  'company_profile.logo_changed': $localize`:@@auditAction.company_profile_logo_changed:Company logo changed`,
  'company_profile.logo_removed': $localize`:@@auditAction.company_profile_logo_removed:Company logo removed`,
  'compliance.document_recorded': $localize`:@@auditAction.compliance_document_recorded:Compliance document recorded`,
  'compliance.document_refused': $localize`:@@auditAction.compliance_document_refused:Compliance document refused`,
  'compliance.document_withdrawn': $localize`:@@auditAction.compliance_document_withdrawn:Compliance document withdrawn`,
  'compliance.type_created': $localize`:@@auditAction.compliance_type_created:Compliance document type created`,
  'compliance.type_updated': $localize`:@@auditAction.compliance_type_updated:Compliance document type updated`,
  'compliance.vendor_status_set': $localize`:@@auditAction.compliance_vendor_status_set:Vendor registration status set`,
  'decision.approved': $localize`:@@auditAction.decision_approved:Decision approved`,
  'decision.draft_saved': $localize`:@@auditAction.decision_draft_saved:Decision draft saved`,
  'decision.override_recorded': $localize`:@@auditAction.decision_override_recorded:Recommendation override recorded`,
  'decision.pack_generated': $localize`:@@auditAction.decision_pack_generated:Decision pack generated`,
  'decision.rejected': $localize`:@@auditAction.decision_rejected:Decision rejected`,
  'decision.returned': $localize`:@@auditAction.decision_returned:Decision returned`,
  'decision.submitted': $localize`:@@auditAction.decision_submitted:Decision submitted for approval`,
  'decision.withdrawn': $localize`:@@auditAction.decision_withdrawn:Decision withdrawn from approval`,
  'evaluation.adjustment_carried': $localize`:@@auditAction.evaluation_adjustment_carried:Leveling adjustment carried to the new round`,
  'evaluation.adjustment_recorded': $localize`:@@auditAction.evaluation_adjustment_recorded:Leveling adjustment recorded`,
  'evaluation.adjustment_withdrawn': $localize`:@@auditAction.evaluation_adjustment_withdrawn:Leveling adjustment withdrawn`,
  'evaluation.completed': $localize`:@@auditAction.evaluation_completed:Evaluation completed`,
  'evaluation.evaluator_assigned': $localize`:@@auditAction.evaluation_evaluator_assigned:Evaluator assigned`,
  'evaluation.evaluator_removed': $localize`:@@auditAction.evaluation_evaluator_removed:Evaluator removed`,
  'evaluation.leveling_completed': $localize`:@@auditAction.evaluation_leveling_completed:Commercial leveling completed`,
  'evaluation.leveling_exported': $localize`:@@auditAction.evaluation_leveling_exported:Commercial leveling exported`,
  'evaluation.leveling_reopened': $localize`:@@auditAction.evaluation_leveling_reopened:Commercial leveling reopened`,
  'evaluation.note_added': $localize`:@@auditAction.evaluation_note_added:Evaluation note added`,
  'evaluation.policy_changed': $localize`:@@auditAction.evaluation_policy_changed:Evaluation scorecard policy changed`,
  'evaluation.reopened': $localize`:@@auditAction.evaluation_reopened:Evaluation reopened`,
  'evaluation.round_refreshed': $localize`:@@auditAction.evaluation_round_refreshed:Evaluation refreshed after a negotiation round`,
  'evaluation.scorecard_reopened': $localize`:@@auditAction.evaluation_scorecard_reopened:Scorecard reopened`,
  'evaluation.scorecard_submitted': $localize`:@@auditAction.evaluation_scorecard_submitted:Scorecard submitted`,
  'evaluation.started': $localize`:@@auditAction.evaluation_started:Evaluation started`,
  'evaluation.thresholds_changed': $localize`:@@auditAction.evaluation_thresholds_changed:Evaluation thresholds changed`,
  'evaluation_policy.created': $localize`:@@auditAction.evaluation_policy_created:Scorecard policy created`,
  'evaluation_policy.status_changed': $localize`:@@auditAction.evaluation_policy_status_changed:Scorecard policy status changed`,
  'evaluation_policy.updated': $localize`:@@auditAction.evaluation_policy_updated:Scorecard policy updated`,
  'evaluation_policy.version_added': $localize`:@@auditAction.evaluation_policy_version_added:Scorecard policy version added`,
  'file.withheld': $localize`:@@auditAction.file_withheld:File withheld by the malware scan`,
  'invitation.declined': $localize`:@@auditAction.invitation_declined:Firm declined`,
  'invitation.email_failed': $localize`:@@auditAction.invitation_email_failed:Invitation email failed`,
  'invitation.email_sent': $localize`:@@auditAction.invitation_email_sent:Invitation email sent`,
  'invitation.intends_to_bid': $localize`:@@auditAction.invitation_intends_to_bid:Firm intends to bid`,
  'invitation.link_copied': $localize`:@@auditAction.invitation_link_copied:Firm link copied`,
  'invitation.link_regenerated': $localize`:@@auditAction.invitation_link_regenerated:Firm link regenerated`,
  'invitation.opened': $localize`:@@auditAction.invitation_opened:Invitation opened by the firm`,
  'invitation.recipient_changed': $localize`:@@auditAction.invitation_recipient_changed:Invitation recipient changed`,
  'invitation.reminder_requested': $localize`:@@auditAction.invitation_reminder_requested:Reminder requested for a firm`,
  'invitation.resend_requested': $localize`:@@auditAction.invitation_resend_requested:Invitation resend requested`,
  'invitation.revoked': $localize`:@@auditAction.invitation_revoked:Invitation revoked`,
  'invitation.second_recipient_removed': $localize`:@@auditAction.invitation_second_recipient_removed:Second invitation recipient removed`,
  'invitation.second_recipient_set': $localize`:@@auditAction.invitation_second_recipient_set:Second invitation recipient set`,
  'login.failed': $localize`:@@auditAction.login_failed:Sign-in failed`,
  'login.succeeded': $localize`:@@auditAction.login_succeeded:Signed in`,
  'login.throttled': $localize`:@@auditAction.login_throttled:Sign-ins paused after repeated failures`,
  'negotiation.attachment_added': $localize`:@@auditAction.negotiation_attachment_added:File attached to a negotiation response`,
  'negotiation.attachment_refused': $localize`:@@auditAction.negotiation_attachment_refused:Negotiation file refused`,
  'negotiation.attachment_removed': $localize`:@@auditAction.negotiation_attachment_removed:File removed from a negotiation response`,
  'negotiation.link_replaced': $localize`:@@auditAction.negotiation_link_replaced:Negotiation link replaced`,
  'negotiation.note_added': $localize`:@@auditAction.negotiation_note_added:Negotiation note added`,
  'negotiation.participant_withdrawn': $localize`:@@auditAction.negotiation_participant_withdrawn:Firm withdrawn from a negotiation round`,
  'negotiation.response_declined': $localize`:@@auditAction.negotiation_response_declined:Firm declined the negotiation round`,
  'negotiation.response_resumed': $localize`:@@auditAction.negotiation_response_resumed:Negotiation response resumed`,
  'negotiation.response_started': $localize`:@@auditAction.negotiation_response_started:Negotiation response started`,
  'negotiation.response_submitted': $localize`:@@auditAction.negotiation_response_submitted:Negotiation response submitted`,
  'negotiation.round_cancelled': $localize`:@@auditAction.negotiation_round_cancelled:Negotiation round cancelled`,
  'negotiation.round_closed': $localize`:@@auditAction.negotiation_round_closed:Negotiation round closed`,
  'negotiation.round_issued': $localize`:@@auditAction.negotiation_round_issued:Negotiation round issued`,
  'negotiation.round_viewed': $localize`:@@auditAction.negotiation_round_viewed:Negotiation round viewed by the firm`,
  'opening.bid_withdrawn': $localize`:@@auditAction.opening_bid_withdrawn:Bid withdrawn at opening`,
  'opening.file_classified': $localize`:@@auditAction.opening_file_classified:Opened bid file classified`,
  'opening.file_downloaded': $localize`:@@auditAction.opening_file_downloaded:Opened bid file downloaded`,
  'password_reset.completed': $localize`:@@auditAction.password_reset_completed:Password reset completed`,
  'password_reset.forced': $localize`:@@auditAction.password_reset_forced:Password reset forced`,
  'password_reset.requested': $localize`:@@auditAction.password_reset_requested:Password reset requested`,
  'performance.closeout_finalized': $localize`:@@auditAction.performance_closeout_finalized:Closeout finalized`,
  'performance.closeout_reopened': $localize`:@@auditAction.performance_closeout_reopened:Closeout reopened`,
  'performance.closeout_started': $localize`:@@auditAction.performance_closeout_started:Closeout started`,
  'performance.commercial_saved': $localize`:@@auditAction.performance_commercial_saved:Closeout commercial outcome saved`,
  'performance.execution_saved': $localize`:@@auditAction.performance_execution_saved:Closeout execution outcome saved`,
  'project.assignment_changed': $localize`:@@auditAction.project_assignment_changed:Project Manager assignment changed`,
  'project.created': $localize`:@@auditAction.project_created:Project created`,
  'project.currency_changed': $localize`:@@auditAction.project_currency_changed:Project currency changed`,
  'project.status_changed': $localize`:@@auditAction.project_status_changed:Project status changed`,
  'project.updated': $localize`:@@auditAction.project_updated:Project updated`,
  'recommendation.computed': $localize`:@@auditAction.recommendation_computed:Recommendation computed`,
  'recommendation_policy.created': $localize`:@@auditAction.recommendation_policy_created:Recommendation policy created`,
  'recommendation_policy.status_changed': $localize`:@@auditAction.recommendation_policy_status_changed:Recommendation policy status changed`,
  'recommendation_policy.updated': $localize`:@@auditAction.recommendation_policy_updated:Recommendation policy updated`,
  'recommendation_policy.version_added': $localize`:@@auditAction.recommendation_policy_version_added:Recommendation policy version added`,
  'retrospective.commercial_saved': $localize`:@@auditAction.retrospective_commercial_saved:Past outcome commercial details saved`,
  'retrospective.confirmed': $localize`:@@auditAction.retrospective_confirmed:Past outcome confirmed`,
  'retrospective.correction_started': $localize`:@@auditAction.retrospective_correction_started:Past outcome correction started`,
  'retrospective.created': $localize`:@@auditAction.retrospective_created:Past outcome recorded`,
  'retrospective.execution_saved': $localize`:@@auditAction.retrospective_execution_saved:Past outcome execution details saved`,
  'retrospective.imported': $localize`:@@auditAction.retrospective_imported:Past outcomes imported`,
  'security_policy.changed': $localize`:@@auditAction.security_policy_changed:Sign-in security changed`,
  'session.revoked': $localize`:@@auditAction.session_revoked:Signed out on all devices`,
  'session.signed_out': $localize`:@@auditAction.session_signed_out:Signed out`,
  'sourcing.approval_request_cleared': $localize`:@@auditAction.sourcing_approval_request_cleared:Shortlist approval request cleared by a change`,
  'sourcing.candidate_added': $localize`:@@auditAction.sourcing_candidate_added:Candidate firm added`,
  'sourcing.candidate_assessed': $localize`:@@auditAction.sourcing_candidate_assessed:Candidate firm prequalified`,
  'sourcing.candidate_removed': $localize`:@@auditAction.sourcing_candidate_removed:Candidate firm removed`,
  'sourcing.candidate_shortlisted': $localize`:@@auditAction.sourcing_candidate_shortlisted:Firm added to the shortlist`,
  'sourcing.candidate_unshortlisted': $localize`:@@auditAction.sourcing_candidate_unshortlisted:Firm taken off the shortlist`,
  'sourcing.candidates_added': $localize`:@@auditAction.sourcing_candidates_added:Candidate firms added`,
  'sourcing.candidates_assessed': $localize`:@@auditAction.sourcing_candidates_assessed:Candidate firms prequalified`,
  'sourcing.fast_path_approved': $localize`:@@auditAction.sourcing_fast_path_approved:Shortlist approved on the fast path`,
  'sourcing.reopened': $localize`:@@auditAction.sourcing_reopened:Sourcing reopened`,
  'sourcing.shortlist_approval_requested': $localize`:@@auditAction.sourcing_shortlist_approval_requested:Shortlist approval requested`,
  'sourcing.shortlist_approved': $localize`:@@auditAction.sourcing_shortlist_approved:Shortlist approved`,
  'sourcing.started': $localize`:@@auditAction.sourcing_started:Sourcing started`,
  'sourcing.updated': $localize`:@@auditAction.sourcing_updated:Sourcing updated`,
  'subcontractor.contact_erased': $localize`:@@auditAction.subcontractor_contact_erased:Subcontractor contact erased`,
  'subcontractor.created': $localize`:@@auditAction.subcontractor_created:Subcontractor added`,
  'subcontractor.imported': $localize`:@@auditAction.subcontractor_imported:Subcontractors imported`,
  'subcontractor.status_changed': $localize`:@@auditAction.subcontractor_status_changed:Subcontractor status changed`,
  'subcontractor.updated': $localize`:@@auditAction.subcontractor_updated:Subcontractor updated`,
  'tender.automatic_reminders_queued': $localize`:@@auditAction.tender_automatic_reminders_queued:Automatic reminders queued`,
  'tender.bids_opened': $localize`:@@auditAction.tender_bids_opened:Bids opened`,
  'tender.cancelled': $localize`:@@auditAction.tender_cancelled:Tender cancelled`,
  'tender.closed_early': $localize`:@@auditAction.tender_closed_early:Tender closed early`,
  'tender.closed_for_retender': $localize`:@@auditAction.tender_closed_for_retender:Tender closed for re-tendering`,
  'tender.created': $localize`:@@auditAction.tender_created:Tender created`,
  'tender.deadline_extended': $localize`:@@auditAction.tender_deadline_extended:Deadline extended`,
  'tender.document_added': $localize`:@@auditAction.tender_document_added:Tender document added`,
  'tender.document_removed': $localize`:@@auditAction.tender_document_removed:Tender document removed`,
  'tender.invitation_added': $localize`:@@auditAction.tender_invitation_added:Firm invited after publication`,
  'tender.invitee_added': $localize`:@@auditAction.tender_invitee_added:Firm invited`,
  'tender.invitee_recipient_changed': $localize`:@@auditAction.tender_invitee_recipient_changed:Invited firm recipient changed`,
  'tender.invitee_removed': $localize`:@@auditAction.tender_invitee_removed:Invited firm removed`,
  'tender.invitees_added': $localize`:@@auditAction.tender_invitees_added:Firms invited`,
  'tender.publish_request_cleared': $localize`:@@auditAction.tender_publish_request_cleared:Ready-to-publish mark cleared by a change`,
  'tender.publish_requested': $localize`:@@auditAction.tender_publish_requested:Tender marked ready to publish`,
  'tender.published': $localize`:@@auditAction.tender_published:Tender published`,
  'tender.updated': $localize`:@@auditAction.tender_updated:Tender updated`,
  'tender_template.created': $localize`:@@auditAction.tender_template_created:Tender template created`,
  'tender_template.updated': $localize`:@@auditAction.tender_template_updated:Tender template updated`,
  'tender_template.version_added': $localize`:@@auditAction.tender_template_version_added:Tender template version added`,
  'trade.created': $localize`:@@auditAction.trade_created:Trade created`,
  'trade.status_changed': $localize`:@@auditAction.trade_status_changed:Trade status changed`,
  'trade.updated': $localize`:@@auditAction.trade_updated:Trade updated`,
  'user.erased': $localize`:@@auditAction.user_erased:User erased`,
  'user.invitation_accepted': $localize`:@@auditAction.user_invitation_accepted:Invitation accepted`,
  'user.invitation_resent': $localize`:@@auditAction.user_invitation_resent:Invitation resent`,
  'user.invitation_revoked': $localize`:@@auditAction.user_invitation_revoked:Invitation withdrawn`,
  'user.invited': $localize`:@@auditAction.user_invited:User invited`,
  'user.mfa_enrolled': $localize`:@@auditAction.user_mfa_enrolled:Authenticator set up`,
  'user.mfa_recovery_code_used': $localize`:@@auditAction.user_mfa_recovery_code_used:Recovery code used to sign in`,
  'user.mfa_reset': $localize`:@@auditAction.user_mfa_reset:Authenticator reset`,
  'user.reactivated': $localize`:@@auditAction.user_reactivated:Access restored`,
  'user.role_changed': $localize`:@@auditAction.user_role_changed:Role changed`,
  'user.roles_changed': $localize`:@@auditAction.user_roles_changed:Roles changed`,
  'user.suspended': $localize`:@@auditAction.user_suspended:Access suspended`,
  'work_package.created': $localize`:@@auditAction.work_package_created:Work package created`,
  'work_package.estimate_revised': $localize`:@@auditAction.work_package_estimate_revised:Work package estimate revised`,
  'work_package.status_changed': $localize`:@@auditAction.work_package_status_changed:Work package status changed`,
  'work_package.updated': $localize`:@@auditAction.work_package_updated:Work package updated`,
});

const objects = (): Readonly<Record<string, string>> => ({
  addendum: $localize`:@@auditObject.addendum:Addendum`,
  admin: $localize`:@@auditObject.admin:Company Admin`,
  approval_matrix: $localize`:@@auditObject.approval_matrix:Approval rules`,
  approval_rule: $localize`:@@auditObject.approval_rule:Approval rule`,
  audit: $localize`:@@auditObject.audit:Audit log`,
  award: $localize`:@@auditObject.award:Award`,
  bid: $localize`:@@auditObject.bid:Bid`,
  category_mapping: $localize`:@@auditObject.category_mapping:Category mapping`,
  clarification: $localize`:@@auditObject.clarification:Clarification`,
  company: $localize`:@@auditObject.company:Company`,
  company_email: $localize`:@@auditObject.company_email:Company email`,
  company_profile: $localize`:@@auditObject.company_profile:Company profile`,
  compliance: $localize`:@@auditObject.compliance:Compliance`,
  decision: $localize`:@@auditObject.decision:Decision`,
  evaluation: $localize`:@@auditObject.evaluation:Evaluation`,
  evaluation_policy: $localize`:@@auditObject.evaluation_policy:Scorecard policy`,
  file: $localize`:@@auditObject.file:File`,
  invitation: $localize`:@@auditObject.invitation:Invitation`,
  login: $localize`:@@auditObject.login:Sign-in`,
  membership: $localize`:@@auditObject.membership:Membership`,
  negotiation: $localize`:@@auditObject.negotiation:Negotiation`,
  opening: $localize`:@@auditObject.opening:Opening`,
  password_reset: $localize`:@@auditObject.password_reset:Password reset`,
  performance: $localize`:@@auditObject.performance:Closeout`,
  project: $localize`:@@auditObject.project:Project`,
  recommendation: $localize`:@@auditObject.recommendation:Recommendation`,
  recommendation_policy: $localize`:@@auditObject.recommendation_policy:Recommendation policy`,
  retrospective: $localize`:@@auditObject.retrospective:Past outcome`,
  security_policy: $localize`:@@auditObject.security_policy:Sign-in security`,
  session: $localize`:@@auditObject.session:Session`,
  sourcing: $localize`:@@auditObject.sourcing:Sourcing`,
  subcontractor: $localize`:@@auditObject.subcontractor:Subcontractor`,
  tender: $localize`:@@auditObject.tender:Tender`,
  tender_invitation: $localize`:@@auditObject.tender_invitation:Invitation`,
  tender_template: $localize`:@@auditObject.tender_template:Tender template`,
  trade: $localize`:@@auditObject.trade:Trade`,
  user: $localize`:@@auditObject.user:User`,
  work_package: $localize`:@@auditObject.work_package:Work package`,
});

/** Every action with a curated label (the spec compares it with the committed emitted list). */
export function curatedAuditActions(): readonly string[] {
  return Object.keys(catalogue().actions);
}

/** "tender.deadline_extended" → "Deadline extended"; an uncurated action of a known object → "Tender event"; otherwise "Recorded event". */
export function auditActionLabel(action: string): string {
  const { actions, objects } = catalogue();
  const named = actions[action];
  if (named) return named;
  const noun = objects[action.split('.')[0]];
  return noun
    ? $localize`:@@auditAction.fallbackObject:${noun}:object: event`
    : $localize`:@@auditAction.unknownEvent:Recorded event`;
}
