import {
  CategoryPerformance,
  CloseoutAccess,
  CloseoutWorkspace,
  SubcontractorPerformance,
} from './performance.api';

// Test fixtures shaped exactly like the C# contracts (money and percentages as strings).

export const PM_ACCESS: CloseoutAccess = {
  editCommercial: false,
  editExecution: true,
  finalize: true,
  reopen: false,
};

export const QS_ACCESS: CloseoutAccess = {
  editCommercial: true,
  editExecution: false,
  finalize: false,
  reopen: false,
};

const BASE_REQUIREMENTS = [
  'actual_final_cost',
  'actual_start_date',
  'actual_completion_date',
  'quality_rating',
  'hse_rating',
  'variations',
  'claims',
  'disputes',
  'would_work_again',
];

export function pendingCloseout(access: CloseoutAccess = PM_ACCESS): CloseoutWorkspace {
  return {
    awardId: 'a1',
    lifecycle: 'Pending',
    version: null,
    baseline: {
      awardId: 'a1',
      tenderId: 't1',
      tenderReference: 'TND-2026-0007',
      tenderTitle: 'HVAC works',
      projectCode: 'P-100',
      projectName: 'Tower A',
      workPackageId: 'w1',
      workPackageCode: 'WP-HVAC',
      workPackageTitle: 'HVAC supply and install',
      category: 'Mechanical',
      subcontractorId: 's1',
      subcontractorCode: 'ACME-01',
      subcontractorName: 'ACME Contracting',
      awardValue: '500000.00',
      currency: 'QAR',
      plannedDurationDays: 90,
      mobilizationCommitment: null,
      scopeCompliance: 'Full',
      warrantyMonths: 12,
      exclusions: ['Crane hire'],
      commercialDeviationCount: 0,
      technicalDeviationCount: 1,
      technicalMeanAtAward: 92,
      awardedAtUtc: '2026-03-01T09:00:00Z',
      baselineSha256: 'a'.repeat(64),
      baselineVerified: true,
    },
    commercial: {
      actualFinalCost: null,
      costExplanation: null,
      variationCount: null,
      variationValue: null,
      variationCause: null,
      variationNote: null,
      claimCount: null,
      claimedValue: null,
      unresolvedClaimCount: null,
      claimNote: null,
      disputeCount: null,
      unresolvedDisputeCount: null,
      disputeNote: null,
      commercialFeedback: null,
      evidenceNote: null,
      sectionVersion: null,
      updatedAtUtc: null,
      updatedByName: null,
    },
    execution: {
      actualStartDate: null,
      actualCompletionDate: null,
      scheduleExplanation: null,
      mobilization: null,
      mobilizationNote: null,
      qualityRating: null,
      qualityComment: null,
      hseRating: null,
      hseComment: null,
      executionFeedback: null,
      wouldWorkAgain: null,
      wouldWorkAgainRationale: null,
      evidenceNote: null,
      sectionVersion: null,
      updatedAtUtc: null,
      updatedByName: null,
    },
    metrics: {
      awardValue: '500000.00',
      actualFinalCost: null,
      costVarianceAmount: null,
      costVariancePercent: null,
      plannedDurationDays: 90,
      actualDurationDays: null,
      durationVarianceDays: null,
      scheduleVariancePercent: null,
      scheduleOutcome: null,
      impliedCompletionDate: null,
      actualCompletionDate: null,
    },
    completeness: { complete: false, recorded: 0, required: 9, missing: BASE_REQUIREMENTS },
    currentVersionNumber: 0,
    closedAtUtc: null,
    closedByName: null,
    versions: [],
    events: [],
    access,
    serverTimeUtc: '2026-10-01T09:00:00Z',
    commercialVisible: true,
    assignedProjectManagerName: 'Pat Manager',
    assignedToYou: true,
  };
}

/** The BSD example: 500 000 awarded, 555 000 final (+11 %); 90 days awarded, 108 days actual (+20 %). */
export function recordedCloseout(access: CloseoutAccess = PM_ACCESS): CloseoutWorkspace {
  const base = pendingCloseout(access);
  return {
    ...base,
    lifecycle: 'InProgress',
    version: 'v1',
    commercial: {
      ...base.commercial,
      actualFinalCost: '555000.00',
      costExplanation: 'Seven approved variations',
      variationCount: 7,
      variationValue: '48000.00',
      claimCount: 1,
      unresolvedClaimCount: 0,
      disputeCount: 0,
      sectionVersion: 'c1',
      updatedAtUtc: '2026-09-20T09:00:00Z',
      updatedByName: 'Quinn QS',
    },
    execution: {
      ...base.execution,
      actualStartDate: '2026-04-01',
      actualCompletionDate: '2026-07-17',
      scheduleExplanation: 'Late client approvals',
      mobilization: 'AsPlanned',
      qualityRating: 5,
      hseRating: 4,
      wouldWorkAgain: 'Yes',
      sectionVersion: 'e1',
      updatedAtUtc: '2026-09-21T09:00:00Z',
      updatedByName: 'Pat Manager',
    },
    metrics: {
      awardValue: '500000.00',
      actualFinalCost: '555000.00',
      costVarianceAmount: '55000.00',
      costVariancePercent: '11.00',
      plannedDurationDays: 90,
      actualDurationDays: 108,
      durationVarianceDays: 18,
      scheduleVariancePercent: '20.00',
      scheduleOutcome: 'Late',
      impliedCompletionDate: '2026-06-29',
      actualCompletionDate: '2026-07-17',
    },
    completeness: { complete: true, recorded: 11, required: 11, missing: [] },
  };
}

export function closedCloseout(access: CloseoutAccess): CloseoutWorkspace {
  const recorded = recordedCloseout(access);
  return {
    ...recorded,
    lifecycle: 'Closed',
    version: 'v2',
    currentVersionNumber: 1,
    closedAtUtc: '2026-09-25T09:00:00Z',
    closedByName: 'Pat Manager',
    versions: [
      {
        number: 1,
        authoritative: true,
        finalizedAtUtc: '2026-09-25T09:00:00Z',
        finalizedByName: 'Pat Manager',
        actualFinalCost: '555000.00',
        costVariancePercent: '11.00',
        actualDurationDays: 108,
        scheduleVariancePercent: '20.00',
        qualityRating: 5,
        hseRating: 4,
        variationCount: 7,
        claimCount: 1,
        disputeCount: 0,
        wouldWorkAgain: 'Yes',
        sha256: 'b'.repeat(64),
        fingerprintVerified: true,
      },
    ],
    events: [
      {
        kind: 'Started',
        versionNumber: 0,
        atUtc: '2026-09-20T09:00:00Z',
        actorName: 'Quinn QS',
        reason: null,
      },
      {
        kind: 'Finalized',
        versionNumber: 1,
        atUtc: '2026-09-25T09:00:00Z',
        actorName: 'Pat Manager',
        reason: null,
      },
    ],
  };
}

export function mechanical(sampleSize = 1): CategoryPerformance {
  return {
    category: 'Mechanical',
    sampleSize,
    earliestClosedAtUtc: '2026-09-25T09:00:00Z',
    latestClosedAtUtc: '2026-09-25T09:00:00Z',
    qualityMean: '5.00',
    hseMean: '4.00',
    costVarianceMin: '11.00',
    costVarianceMax: '11.00',
    scheduleVarianceMin: '20.00',
    scheduleVarianceMax: '20.00',
    withinDuration: 0,
    late: 1,
    noDurationBaseline: 0,
    variations: 7,
    claims: 1,
    disputes: 0,
    unresolvedDisputes: 0,
    wouldWorkAgainYes: 1,
    wouldWorkAgainConditional: 0,
    wouldWorkAgainNo: 0,
    outcomes: [
      {
        awardId: 'a1',
        versionNumber: 1,
        tenderReference: 'TND-2026-0007',
        projectCode: 'P-100',
        workPackageCode: 'WP-HVAC',
        workPackageTitle: 'HVAC supply and install',
        category: 'Mechanical',
        awardedAtUtc: '2026-03-01T09:00:00Z',
        closedAtUtc: '2026-09-25T09:00:00Z',
        currency: 'QAR',
        awardValue: '500000.00',
        actualFinalCost: '555000.00',
        costVariancePercent: '11.00',
        plannedDurationDays: 90,
        actualDurationDays: 108,
        scheduleVariancePercent: '20.00',
        scheduleOutcome: 'Late',
        mobilization: 'AsPlanned',
        qualityRating: 5,
        hseRating: 4,
        variationCount: 7,
        variationValue: '48000.00',
        claimCount: 1,
        claimedValue: null,
        unresolvedClaimCount: 0,
        disputeCount: 0,
        unresolvedDisputeCount: 0,
        wouldWorkAgain: 'Yes',
      },
    ],
  };
}

export function history(
  categories: CategoryPerformance[] = [mechanical()],
): SubcontractorPerformance {
  return {
    subcontractorId: 's1',
    subcontractorCode: 'ACME-01',
    subcontractorName: 'ACME Contracting',
    completedProjects: categories.reduce((sum, item) => sum + item.sampleSize, 0),
    categories,
    inCorrection: 0,
    inProgress: 1,
    commercialVisible: true,
  };
}
