import {
  ApprovalMatrix,
  Award,
  DecisionAccess,
  DecisionSubmission,
  CandidateControl,
  DecisionControls,
  DecisionWorkspace,
  NegotiationRound,
  NegotiationWorkspace,
  Recommendation,
  RecommendationCandidate,
  RecommendationPolicy,
  RevisionComparison,
} from './decision.api';
import { BidderNegotiation } from '../bidder/bidder-negotiation.api';

// Test data shared by the English and Arabic Part 10 specs.

const localTime = (utc: string) => ({ utc, local: utc.slice(0, 16), offset: '+00:00' });

export const FULL_DECISION_ACCESS: DecisionAccess = {
  compute: true,
  prepare: true,
  override: true,
  submit: true,
  approve: true,
  issue: true,
  managePolicy: true,
  manageApprovalMatrix: true,
  withdraw: true,
};

export function round(overrides: Partial<NegotiationRound> = {}): NegotiationRound {
  return {
    id: 'r1',
    number: 1,
    type: 'Bafo',
    scope: 'Commercial',
    status: 'Open',
    purpose: 'Close the price gap',
    instructions: 'Please confirm your best and final price.',
    responseDeadline: localTime('2099-10-10T12:00:00Z'),
    deadlinePassed: false,
    issuedAtUtc: '2026-10-05T09:00:00Z',
    issuedByName: 'Maha Manager',
    closedAtUtc: null,
    closedByName: null,
    closureKind: null,
    earlyCloseReason: null,
    cancelledAtUtc: null,
    cancelledByName: null,
    cancellationReason: null,
    participants: [
      {
        id: 'p1',
        openingBidId: 'b1',
        subcontractorCode: 'ACME-01',
        subcontractorName: 'Acme Mechanical',
        recipientName: 'Rana Estimator',
        recipientEmail: 'rana@acme.example',
        status: 'Started',
        baseRevisionNumber: 1,
        submittedRevisionNumber: null,
        firstViewedAtUtc: '2026-10-05T10:00:00Z',
        startedAtUtc: '2026-10-05T10:05:00Z',
        submittedAtUtc: null,
        declinedAtUtc: null,
        withdrawnAtUtc: null,
        withdrawnByName: null,
        emailStatus: 'Sent',
        version: 'pv1',
      },
    ],
    submittedCount: 0,
    version: 'rv1',
    ...overrides,
  };
}

export function negotiation(overrides: Partial<NegotiationWorkspace> = {}): NegotiationWorkspace {
  return {
    tenderId: 't1',
    tenderReference: 'TND-2026-0009',
    tenderTitle: 'HVAC installation',
    timeZoneId: 'Asia/Qatar',
    tenderCancelled: false,
    tenderAwarded: false,
    issueBlocker: null,
    issueBlockerReason: null,
    maximumRounds: 5,
    rounds: [],
    candidates: [
      {
        openingBidId: 'b1',
        subcontractorCode: 'ACME-01',
        subcontractorName: 'Acme Mechanical',
        currentRevisionNumber: 1,
        currentRound: 0,
        invitable: true,
        blocker: null,
      },
      {
        openingBidId: 'b2',
        subcontractorCode: 'BETA-01',
        subcontractorName: 'Beta Contracting',
        currentRevisionNumber: 2,
        currentRound: 1,
        invitable: true,
        blocker: null,
      },
      {
        openingBidId: 'b3',
        subcontractorCode: 'GAMA-01',
        subcontractorName: 'Gama Works',
        currentRevisionNumber: 1,
        currentRound: 0,
        invitable: false,
        blocker: 'invitation_revoked',
      },
    ],
    notes: [],
    access: { manage: true, note: true, viewCommercial: true, viewTechnical: true },
    serverNowUtc: '2026-10-05T11:00:00Z',
    ...overrides,
  };
}

export function comparison(overrides: Partial<RevisionComparison> = {}): RevisionComparison {
  return {
    tenderId: 't1',
    tenderReference: 'TND-2026-0009',
    currency: 'QAR',
    includesCommercial: true,
    bids: [
      {
        openingBidId: 'b1',
        position: 1,
        subcontractorCode: 'ACME-01',
        subcontractorName: 'Acme Mechanical',
        revisions: [
          {
            revisionId: 'v1',
            number: 1,
            round: 0,
            kind: 'Submission',
            submittedAtUtc: '2026-10-02T09:00:00Z',
            contentSha256: 'a'.repeat(64),
            isOpened: true,
            isCurrent: false,
          },
          {
            revisionId: 'v2',
            number: 2,
            round: 1,
            kind: 'Bafo',
            submittedAtUtc: '2026-10-06T09:00:00Z',
            contentSha256: 'b'.repeat(64),
            isOpened: false,
            isCurrent: true,
          },
        ],
        originalTotal: '2000000.00',
        finalTotal: '1800000.00',
        absoluteChange: '-200000.00',
        percentChange: '-10.0',
        fields: [
          {
            field: 'scopeCompliance',
            section: 'technical',
            values: ['Full', 'Full'],
            changedFromPrevious: [false, false],
            changedFromOriginal: false,
          },
          {
            field: 'totalAmount',
            section: 'commercial',
            values: ['2000000.00', '1800000.00'],
            changedFromPrevious: [false, true],
            changedFromOriginal: true,
          },
        ],
        lines: [
          {
            description: 'Supply of AHUs',
            amounts: ['1500000.00', '1300000.00'],
            change: 'changed',
          },
          { description: 'Installation', amounts: ['500000.00', '500000.00'], change: 'unchanged' },
          { description: 'Commissioning', amounts: [null, '0.00'], change: 'added' },
        ],
        lists: [
          {
            field: 'exclusions',
            section: 'commercial',
            text: 'Crane hire',
            statedIn: [true, false],
          },
        ],
        files: [{ fileName: 'boq.xlsx', classification: 'Commercial', presentIn: [true, true] }],
        technicalChanged: false,
        commercialChanged: true,
      },
    ],
    ...overrides,
  };
}

export function candidate(
  overrides: Partial<RecommendationCandidate> = {},
): RecommendationCandidate {
  return {
    openingBidId: 'b1',
    subcontractorCode: 'ACME-01',
    subcontractorName: 'Acme Mechanical',
    bidRevisionNumber: 2,
    round: 1,
    submittedTotal: '1800000.00',
    leveledTotal: '1800000.00',
    technicalMean: 82.5,
    eligible: true,
    ineligibleReason: null,
    rank: 1,
    tied: false,
    total: 91.25,
    criteria: [
      {
        kind: 'Commercial',
        source: 'Current',
        weight: 60,
        appliedWeight: 75,
        status: 'Available',
        input: '1800000.00',
        baseline: '1800000.00',
        score: 100,
        contribution: 75,
      },
      {
        kind: 'Technical',
        source: 'Current',
        weight: 20,
        appliedWeight: 25,
        status: 'Available',
        input: '82.5',
        baseline: null,
        score: 82.5,
        contribution: 20.625,
      },
      {
        kind: 'PastPerformance',
        source: 'Historical',
        weight: 20,
        appliedWeight: 0,
        status: 'Unavailable',
        input: null,
        baseline: null,
        score: null,
        contribution: null,
      },
    ],
    flags: ['revised_in_round', 'no_history'],
    ...overrides,
  };
}

export function recommendation(overrides: Partial<Recommendation> = {}): Recommendation {
  return {
    id: 'rec1',
    number: 1,
    liveState: 'InsufficientHistory',
    staleReason: null,
    computedState: 'InsufficientHistory',
    history: 'Unavailable',
    reducedConfidence: true,
    policyId: 'pol1',
    policyName: 'Balanced award',
    policyVersionNumber: 1,
    currentPolicyVersionNumber: 1,
    minimumTechnicalScore: 60,
    appliedWeightTotal: 80,
    unappliedWeight: 20,
    currency: 'QAR',
    evaluationRound: 1,
    evaluationCompletedAtUtc: '2026-10-07T09:00:00Z',
    computedAtUtc: '2026-10-07T10:00:00Z',
    computedByName: 'Maha Manager',
    evidenceFingerprint: 'f'.repeat(64),
    candidates: [
      candidate(),
      candidate({
        openingBidId: 'b2',
        subcontractorCode: 'BETA-01',
        subcontractorName: 'Beta Contracting',
        bidRevisionNumber: 1,
        round: 0,
        submittedTotal: '1900000.00',
        leveledTotal: '1950000.00',
        rank: 2,
        total: 80.1,
        flags: [],
      }),
      candidate({
        openingBidId: 'b3',
        subcontractorCode: 'GAMA-01',
        subcontractorName: 'Gama Works',
        bidRevisionNumber: 1,
        round: 0,
        eligible: false,
        ineligibleReason: 'below_technical_threshold',
        rank: null,
        total: null,
        technicalMean: 41,
        criteria: [],
        flags: [],
      }),
    ],
    minimumCompliantBids: 2,
    limitedCompetition: false,
    ...overrides,
  };
}

export function submission(overrides: Partial<DecisionSubmission> = {}): DecisionSubmission {
  return {
    id: 's1',
    number: 1,
    recommendationId: 'rec1',
    recommendationNumber: 1,
    proposedOpeningBidId: 'b2',
    subcontractorCode: 'BETA-01',
    subcontractorName: 'Beta Contracting',
    bidRevisionNumber: 1,
    round: 0,
    recommendedRank: 2,
    isOverride: true,
    overrideReason: 'Stronger site team for the fast-track programme',
    awardValue: '1950000.00',
    currency: 'QAR',
    leveledTotal: '1950000.00',
    submittedTotal: '1900000.00',
    valueReason: null,
    rationale: 'Best overall value for the programme.',
    dispositions: [
      {
        openingBidId: 'b2',
        subcontractorCode: 'BETA-01',
        subcontractorName: 'Beta Contracting',
        disposition: 'Award',
        reserveRank: null,
        reason: null,
        recommendedRank: 2,
        eligible: true,
      },
      {
        openingBidId: 'b1',
        subcontractorCode: 'ACME-01',
        subcontractorName: 'Acme Mechanical',
        disposition: 'Reserve',
        reserveRank: 1,
        reason: null,
        recommendedRank: 1,
        eligible: true,
      },
      {
        openingBidId: 'b3',
        subcontractorCode: 'GAMA-01',
        subcontractorName: 'Gama Works',
        disposition: 'Reject',
        reserveRank: null,
        reason: 'Below the pass mark',
        recommendedRank: null,
        eligible: false,
      },
    ],
    route: {
      ruleName: 'Up to 5M',
      isDefault: false,
      requiredApprovals: 2,
      steps: [
        {
          step: 1,
          role: 'ApproverDirector',
          approval: {
            id: 'a1',
            submissionNumber: 1,
            kind: 'Approve',
            step: 1,
            actorName: 'Dana Director',
            actorRoles: 'ApproverDirector',
            comment: null,
            actedAtUtc: '2026-10-08T09:00:00Z',
          },
        },
        { step: 2, role: null, approval: null },
      ],
      allowSelfApproval: false,
    },
    submittedAtUtc: '2026-10-07T12:00:00Z',
    submittedByName: 'Maha Manager',
    outcome: 'Pending',
    actions: [
      {
        id: 'a1',
        submissionNumber: 1,
        kind: 'Approve',
        step: 1,
        actorName: 'Dana Director',
        actorRoles: 'ApproverDirector',
        comment: null,
        actedAtUtc: '2026-10-08T09:00:00Z',
      },
    ],
    limitedCompetition: false,
    overBudget: false,
    competitionCategory: null,
    competitionReason: null,
    overBudgetReason: null,
    ...overrides,
  };
}

export function award(overrides: Partial<Award> = {}): Award {
  return {
    id: 'aw1',
    awardedAtUtc: '2026-10-09T09:00:00Z',
    awardedByName: 'Maha Manager',
    subcontractorCode: 'BETA-01',
    subcontractorName: 'Beta Contracting',
    awardValue: '1950000.00',
    currency: 'QAR',
    submissionNumber: 1,
    baseline: {
      id: 'bl1',
      tenderReference: 'TND-2026-0009',
      tenderTitle: 'HVAC installation',
      tenderRevisionInForce: 2,
      workPackageCode: 'HVAC-01',
      workPackageTitle: 'HVAC works',
      workPackageCategory: 'MEP',
      projectCode: 'TWR-1',
      projectName: 'Tower One',
      subcontractorCode: 'BETA-01',
      subcontractorName: 'Beta Contracting',
      bidReference: 'BID-CCCC-DDDD',
      bidRevisionNumber: 1,
      bidRevisionKind: 'Submission',
      round: 0,
      answeredTenderRevision: 2,
      bidContentSha256: 'c'.repeat(64),
      awardValue: '1950000.00',
      currency: 'QAR',
      submittedTotal: '1900000.00',
      leveledTotal: '1950000.00',
      valueReason: null,
      scopeCompliance: 'WithDeviations',
      durationDays: 120,
      validityDays: 90,
      warrantyMonths: 12,
      paymentTerms: '30% advance',
      mobilizationCommitment: null,
      technicalApproach: 'Two crews',
      lines: [{ position: 1, description: 'Supply and install', amount: '1900000.00' }],
      exclusions: ['Crane hire'],
      commercialDeviations: [],
      technicalDeviations: ['Alternative damper brand'],
      awardedAtUtc: '2026-10-09T09:00:00Z',
      submissionNumber: 1,
      recommendationNumber: 1,
      recommendedRank: 2,
      isOverride: true,
      approvalRuleName: 'Up to 5M',
      baselineSha256: 'd'.repeat(64),
      fingerprintVerified: true,
    },
    dispositions: submission().dispositions,
    ...overrides,
  };
}

/** ADR-086: two valid bids of active firms, an estimate the proposed value exceeds by 11.11 %. */
export function controls(overrides: Partial<DecisionControls> = {}): DecisionControls {
  const row = (openingBidId: string, subcontractorCode: string): CandidateControl => ({
    openingBidId,
    subcontractorCode,
    standing: 'Active',
    validityDays: 90,
    validityBasis: 'SubmissionDeadline',
    validFromUtc: '2026-10-01T09:00:00Z',
    validUntilUtc: '2026-12-30T09:00:00Z',
    validityState: 'Valid',
    estimateVariancePercent: '11.11',
  });
  return {
    invited: 4,
    submitted: 3,
    eligible: 3,
    minimumCompliantBids: 2,
    limitedCompetition: false,
    candidates: [row('b1', 'ACME-01'), row('b2', 'BETA-01')],
    estimate: '1620000.00',
    estimateCurrency: 'QAR',
    overBudgetTolerancePercent: '0',
    proposedOverBudget: null,
    proposedVariancePercent: '11.11',
    estimateChangedAfterPublication: false,
    historyCategoryMissing: false,
    ...overrides,
  };
}

export function decision(overrides: Partial<DecisionWorkspace> = {}): DecisionWorkspace {
  return {
    tenderId: 't1',
    tenderReference: 'TND-2026-0009',
    tenderTitle: 'HVAC installation',
    currency: 'QAR',
    readiness: { state: 'Ready', gaps: [] },
    recommendation: recommendation(),
    recommendationHistory: [
      {
        id: 'rec1',
        number: 1,
        computedAtUtc: '2026-10-07T10:00:00Z',
        computedByName: 'Maha Manager',
        policyName: 'Balanced award',
        policyVersionNumber: 1,
        latest: true,
      },
    ],
    policyOptions: [
      { id: 'pol1', name: 'Balanced award', currentVersionNumber: 1, weighsHistory: true },
    ],
    status: null,
    decisionVersion: null,
    draft: null,
    routePreview: null,
    currentSubmission: null,
    submissions: [],
    approvalBlocker: null,
    award: null,
    timeline: [
      {
        kind: 'recommendation_computed',
        atUtc: '2026-10-07T10:00:00Z',
        actorName: 'Maha Manager',
        number: 1,
        step: null,
      },
    ],
    access: FULL_DECISION_ACCESS,
    serverNowUtc: '2026-10-07T11:00:00Z',
    controls: null,
    ...overrides,
  };
}

export function pending(overrides: Partial<DecisionWorkspace> = {}): DecisionWorkspace {
  return decision({
    status: 'PendingApproval',
    decisionVersion: 'dv2',
    currentSubmission: submission(),
    submissions: [submission()],
    ...overrides,
  });
}

export function recommendationPolicy(
  overrides: Partial<RecommendationPolicy> = {},
): RecommendationPolicy {
  const current = {
    id: 'pv1',
    number: 1,
    minimumTechnicalScore: 60,
    createdAtUtc: '2026-10-01T09:00:00Z',
    createdByName: 'Maha Manager',
    lockedAtUtc: '2026-10-07T10:00:00Z',
    criteria: [
      { id: 'c1', position: 1, kind: 'Commercial' as const, weight: 60 },
      { id: 'c2', position: 2, kind: 'Technical' as const, weight: 40 },
    ],
  };
  return {
    id: 'pol1',
    name: 'Balanced award',
    description: null,
    status: 'Active',
    currentVersionNumber: 1,
    current,
    versions: [current],
    updatedAtUtc: '2026-10-01T09:00:00Z',
    version: 'pver1',
    ...overrides,
  };
}

export function matrix(overrides: Partial<ApprovalMatrix> = {}): ApprovalMatrix {
  return {
    rules: [
      {
        id: 'rule1',
        name: 'Up to 5M',
        priority: 10,
        active: true,
        currency: 'QAR',
        minimumValue: '0.00',
        maximumValue: '5000000.00',
        projectId: null,
        category: null,
        requiredApprovals: 2,
        stepRoles: ['ApproverDirector', null],
        allowSelfApproval: false,
        updatedAtUtc: '2026-10-01T09:00:00Z',
        version: 'ruv1',
      },
    ],
    approverRoles: ['CompanyAdmin', 'ApproverDirector'],
    maximumApprovals: 3,
    ...overrides,
  };
}

export function bidderRound(overrides: Partial<BidderNegotiation> = {}): BidderNegotiation {
  return {
    buyerName: 'Delta Construction',
    hasLogo: false,
    tenderReference: 'TND-2026-0009',
    tenderTitle: 'HVAC installation',
    roundNumber: 1,
    type: 'Bafo',
    scope: 'Commercial',
    instructions: 'Please confirm your best and final price.',
    responseDeadline: { utc: '2099-10-10T09:00:00Z', local: '2099-10-10T12:00', offset: '+03:00' },
    timeZoneId: 'Asia/Qatar',
    state: 'open',
    status: 'Invited',
    currency: 'QAR',
    currencyMinorUnits: 2,
    bidReference: 'BID-AAAA-BBBB',
    subcontractorName: 'Acme Mechanical',
    bidValidityDays: 90,
    technicalProposalRequired: true,
    durationRequired: true,
    pricing: null,
    terms: null,
    requiredDocuments: ['Priced BOQ', 'Method statement'],
    currentRevisionNumber: 1,
    currentSubmission: {
      totalAmount: '2000000.00',
      lines: [{ description: 'Supply of AHUs', amount: '2000000.00' }],
      validityDays: 90,
      paymentTerms: null,
      durationDays: 120,
      warrantyMonths: 12,
      exclusions: [],
      commercialDeviations: [],
      commercialNotes: null,
      scopeCompliance: 'Full',
      technicalApproach: 'Two crews',
      technicalDeviations: [],
      technicalNotes: null,
    },
    currentFiles: [],
    draft: null,
    draftVersion: null,
    draftSavedAtUtc: null,
    draftFiles: [],
    gaps: [],
    editable: false,
    receipt: null,
    declineComment: null,
    maximumAttachments: 20,
    maximumAttachmentBytes: 26214400,
    maximumTotalAttachmentBytes: 104857600,
    allowedExtensions: ['.pdf', '.xlsx'],
    contactName: 'Maha Manager',
    contactEmail: 'maha@delta.example',
    serverNowUtc: '2099-10-01T09:00:00Z',
    ...overrides,
  };
}
