import { Dashboard, SampleSummary, SubcontractorIntelligence } from './intelligence.api';

// Part 12 test data shaped exactly like the API: one completed project (a small sample), one decided tender, one declined
// invitation — and the same profile as a technical reader receives it (every commercial, delivery and decision field absent).

const none: SampleSummary = { count: 0, median: null, mean: null, minimum: null, maximum: null };
const one = (value: string): SampleSummary => ({
  count: 1,
  median: null,
  mean: null,
  minimum: value,
  maximum: value,
});

export function fullProfile(
  overrides: Partial<SubcontractorIntelligence> = {},
): SubcontractorIntelligence {
  return {
    subcontractorId: 's1',
    code: 'ACME-01',
    legalName: 'ACME Contracting',
    tradingName: null,
    standing: 'Active',
    trades: ['HVAC'],
    categoryKey: null,
    category: null,
    categories: [
      {
        key: 'MECHANICAL',
        category: 'Mechanical',
        invitations: 2,
        completedProjects: 1,
        latestActivityUtc: '2026-09-20T10:00:00Z',
      },
      {
        key: '',
        category: null,
        invitations: 1,
        completedProjects: 0,
        latestActivityUtc: '2026-08-01T10:00:00Z',
      },
    ],
    access: { commercial: true, performance: true, decisions: true },
    rule: 'intelligence-metrics-v2',
    generatedAtUtc: '2026-09-29T10:00:00Z',
    procurement: {
      issued: 3,
      open: 1,
      revoked: 0,
      cancelled: 0,
      valid: 2,
      submitted: 1,
      declined: 1,
      noResponse: 0,
      reliabilityPercent: '50.0',
      hoursToFirstReply: {
        count: 2,
        median: '15.0',
        mean: '15.0',
        minimum: '6.0',
        maximum: '24.0',
      },
      hoursToFirstSubmission: one('30.0'),
      earliestInvitationUtc: '2026-06-01T10:00:00Z',
      latestInvitationUtc: '2026-09-20T10:00:00Z',
    },
    awards: {
      participations: 1,
      awards: 1,
      awardRatePercent: '100.0',
      awaitingDecision: 0,
      openedThenCancelled: 0,
      reserves: 0,
      rejections: 0,
      items: [
        {
          tenderId: 't1',
          tenderReference: 'TND-2026-0001',
          category: 'Mechanical',
          awardedAtUtc: '2026-07-01T10:00:00Z',
          disposition: 'Award',
          recommendedRank: 1,
          awardWasOverride: false,
          awardId: 'aw1',
          awardState: 'Accepted',
        },
      ],
    },
    competitiveness: {
      tenders: 1,
      compared: 1,
      lowest: 1,
      belowMedian: 1,
      atMedian: 0,
      aboveMedian: 0,
      leveledVersusMedian: one('-4.76'),
      items: [
        {
          tenderId: 't1',
          tenderReference: 'TND-2026-0001',
          category: 'Mechanical',
          computedAtUtc: '2026-06-20T10:00:00Z',
          currency: 'QAR',
          submittedTotal: '1000000.00',
          leveledTotal: '1000000.00',
          comparableBids: 2,
          position: 1,
          tiedPosition: false,
          leveledVersusMedianPercent: '-4.76',
          submittedVersusMedianPercent: '-4.76',
        },
      ],
    },
    evidence: {
      completedProjects: 1,
      earliestClosedAtUtc: '2026-09-01T10:00:00Z',
      latestClosedAtUtc: '2026-09-01T10:00:00Z',
      strength: 'Limited',
      dated: false,
    },
    delivery: {
      onTime: 0,
      late: 1,
      noScheduleBaseline: 0,
      onTimeRatePercent: '0.0',
      costVariance: one('11.00'),
      scheduleVariance: one('20.00'),
      quality: one('4.00'),
      hse: one('5.00'),
      qualityDistribution: [0, 0, 0, 1, 0],
      hseDistribution: [0, 0, 0, 0, 1],
      projectsWithVariations: 1,
      variations: 3,
      projectsWithClaims: 1,
      claims: 1,
      unresolvedClaims: 0,
      projectsWithDisputes: 0,
      disputes: 0,
      unresolvedDisputes: 0,
      wouldWorkAgainYes: 1,
      wouldWorkAgainConditional: 0,
      wouldWorkAgainNo: 0,
      outcomeScore: null,
      outcomeScoreRule: 'performance-outcome-v1',
      outcomes: [
        {
          awardId: 'a1',
          versionNumber: 1,
          tenderReference: 'TND-2026-0001',
          projectCode: 'P-A',
          workPackageCode: 'WP-A',
          workPackageTitle: 'HVAC works A',
          category: 'Mechanical',
          awardedAtUtc: '2026-07-01T10:00:00Z',
          closedAtUtc: '2026-09-01T10:00:00Z',
          costVariancePercent: '11.00',
          plannedDurationDays: 120,
          actualDurationDays: 144,
          scheduleVariancePercent: '20.00',
          scheduleOutcome: 'Late',
          qualityRating: 4,
          hseRating: 5,
          variationCount: 3,
          claimCount: 1,
          unresolvedClaimCount: 0,
          disputeCount: 0,
          unresolvedDisputeCount: 0,
          wouldWorkAgain: 'Yes',
        },
      ],
    },
    similar: null,
    recentParticipation: [
      {
        tenderId: 't2',
        tenderReference: 'TND-2026-0002',
        tenderTitle: 'HVAC works B',
        category: 'Mechanical',
        issuedAtUtc: '2026-09-20T10:00:00Z',
        outcome: 'Open',
        awardedToFirm: false,
      },
      {
        tenderId: 't1',
        tenderReference: 'TND-2026-0001',
        tenderTitle: 'HVAC works A',
        category: 'Mechanical',
        issuedAtUtc: '2026-06-01T10:00:00Z',
        outcome: 'Submitted',
        awardedToFirm: true,
      },
    ],
    truncated: false,
    ...overrides,
  };
}

/** What a technical evaluator receives: general evidence only — the other classes are absent on the wire. */
export function generalProfile(): SubcontractorIntelligence {
  return fullProfile({
    access: { commercial: false, performance: false, decisions: false },
    competitiveness: null,
    delivery: null,
    awards: { ...fullProfile().awards, reserves: null, rejections: null, items: [] },
  });
}

export function emptyProfile(): SubcontractorIntelligence {
  return fullProfile({
    categoryKey: 'ELECTRICAL',
    category: 'Electrical',
    procurement: {
      ...fullProfile().procurement,
      issued: 0,
      open: 0,
      valid: 0,
      submitted: 0,
      declined: 0,
      reliabilityPercent: null,
      hoursToFirstReply: none,
      hoursToFirstSubmission: none,
      earliestInvitationUtc: null,
      latestInvitationUtc: null,
    },
    awards: {
      participations: 0,
      awards: 0,
      awardRatePercent: null,
      awaitingDecision: 0,
      openedThenCancelled: 0,
      reserves: 0,
      rejections: 0,
      items: [],
    },
    competitiveness: {
      ...fullProfile().competitiveness!,
      tenders: 0,
      compared: 0,
      lowest: 0,
      belowMedian: 0,
      leveledVersusMedian: none,
      items: [],
    },
    evidence: {
      completedProjects: 0,
      earliestClosedAtUtc: null,
      latestClosedAtUtc: null,
      strength: 'None',
      dated: false,
    },
    delivery: { ...fullProfile().delivery!, outcomes: [] },
    recentParticipation: [],
  });
}

export function adminDashboard(): Dashboard {
  return {
    generatedAtUtc: '2026-09-29T10:00:00Z',
    portfolio: { activeProjects: 4, onHoldProjects: 1, activeWorkPackages: 9 },
    tenders: {
      drafts: 1,
      openForBids: 2,
      closingSoon: 1,
      awaitingOpening: 1,
      items: [
        {
          kind: 'tender.closing',
          id: 't2',
          tenderId: 't2',
          reference: 'TND-2026-0002',
          title: 'HVAC works B',
          detail: null,
          status: 'Published',
          atUtc: '2026-10-02T10:00:00Z',
        },
        {
          kind: 'tender.awaiting_opening',
          id: 't3',
          tenderId: 't3',
          reference: 'TND-2026-0003',
          title: 'Electrical',
          detail: null,
          status: 'Published',
          atUtc: '2026-09-28T10:00:00Z',
        },
      ],
    },
    evaluation: {
      pending: 1,
      readyForDecision: 0,
      items: [
        {
          kind: 'evaluation.pending',
          id: 't4',
          tenderId: 't4',
          reference: 'TND-2026-0004',
          title: 'Civil',
          detail: null,
          status: 'InProgress',
          atUtc: '2026-09-25T10:00:00Z',
        },
      ],
    },
    decisions: {
      awaitingApproval: 1,
      approvedAwaitingAward: 0,
      items: [
        {
          kind: 'decision.awaiting_approval',
          id: 'd1',
          tenderId: 't5',
          reference: 'TND-2026-0005',
          title: 'Plumbing',
          detail: null,
          status: 'PendingApproval',
          atUtc: '2026-09-27T10:00:00Z',
        },
      ],
      recentAwards: [
        {
          kind: 'award.issued',
          id: 'a1',
          tenderId: 't1',
          reference: 'TND-2026-0001',
          title: null,
          detail: 'ACME-01 · ACME Contracting',
          status: null,
          atUtc: '2026-07-01T10:00:00Z',
        },
      ],
    },
    closeouts: {
      pending: 2,
      inProgress: 1,
      reopened: 0,
      closed: 1,
      recentlyClosed: [
        {
          kind: 'closeout.closed',
          id: 'a1',
          tenderId: null,
          reference: 'TND-2026-0001',
          title: 'WP-A · Mechanical',
          detail: 'ACME-01 · ACME Contracting',
          status: 'Late',
          atUtc: '2026-09-01T10:00:00Z',
        },
      ],
    },
    evidence: {
      firmsWithHistory: 1,
      categories: [
        {
          category: 'Mechanical',
          firms: 1,
          projects: 1,
          firmsWithModerateEvidence: 0,
          latestClosedAtUtc: '2026-09-01T10:00:00Z',
          strongestFirmEvidence: 'Limited',
          dated: false,
        },
      ],
    },
  };
}
